// ==UserScript==
// @name FIMFiction Emote Extender
// @namespace ffemoteextender
// @description Adds additional emotes to fimfiction.net.
// @include http*://www.fimfiction.net/*
// @include http*://fimfiction.net/*
// @grant none
// @require https://raw.github.com/KrazyTheFox/FIMFiction-Emote-API/development/emoteAPI.js
// @version 3.0d
// ==/UserScript==

$(document).ready(run());

function run() {
	
	addEmote("http://i.imgur.com/NBEDt.png", "ajlie", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/5Tp73.png", "ajhappy", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/oa0BJ.png", "ajsup", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/oaEI1BM.png", "ajderp", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/bEP8EQ2.png", "ajgasp", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/mMp7L.png", "ajcower", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/HZlOi.png", "ajsly", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/7PYFy.png", "ajsquinty", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/DHDbq.png", "ajugh", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/8zRAx.png", "ajwut", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/aBIJ1.png", "ajfrown", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/DmoWN.png", "ajhmmm", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/MdJgU.png", "ajconfused", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/dVnqE.png", "ajcarefree", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/TAf9J.png", "ajconfident", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/gNxjD.png", "ajproud", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/JmYib.png", "ajmad", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/aPZth.png", "ajinnocent", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/4sZY1.png", "ajwoozy", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/1NN8f.png", "ajwhat", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/xmRQV.png", "ajskeptical", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/lGb8P.png", "ajcurious", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/0zTKq.png", "ajsmirk", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/BeQHk.png", "ajbiggrin", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/fl6ox.png", "ajcry", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/mbZjl.png", "ajmoustache", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/r19vB.png", "ajbashful", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/hMgvT.png", "ajunamused", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/ZCoEh.png", "ajsalute", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/1ppRy.png", "ajglasses", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/kjSfI.png", "ajhazy", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/pwUmu.png", "ajdiscorded", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/geqle.png", "ajghost", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/LOrxf.png", "ajannoyed", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/Evd0x.png", "ajcrazy", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/tjCXQ.png", "ajeww", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/NlvYtnA.png", "ajooh", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/Qe7TiLt.png", "ajwait", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/yAmRYea.png", "ajangry", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/pww1wjm.png", "ajstubborn", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/KZHFE8U.png", "ajno", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/MZsrxQK.png", "ajunsure", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/aHVIEJf.png", "ajfearful", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/DPk2NZn.png", "ajnotlying", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/ogtnDnC.png", "ajexcited", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/oBAx788.png", "ajwink", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/myOBKB4.png", "ajfaint", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/LRD2W70.png", "ajglare", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/MIrVmT7.png", "ajsad", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/yyfj6BZ.png", "fillyaj", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/6DvjrRv.png", "ajrage", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/0REqcvr.png", "ajcanthearyou", "AJ", "Applejack", 2);

	addEmote("http://i.imgur.com/hCkff.png", "flutterjerk", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/FlxUX.png", "flutterroll", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/Mpt2V.png", "flutterwhoa", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/PKx4m.png", "flutterfear", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/J1YdP.png", "fluttershy", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/iX6uT.png", "flutterserious", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/AUoqx.png", "fluttershh", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/gphLa.png", "flutteryay", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/eAjva.png", "flutterwink", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/H718D.png", "flutterblush", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/ahOjP.png", "flutterloveme", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/5wxoPUa.png", "whattheflut", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/sb2Qbof.png", "fluttersmile", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/24nRCr5.png", "flutterhope", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/AFuKMoD.png", "flutterglee", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/mkCLMHb.png", "flutterfrown", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/IOcuWkK.png", "flutterstern", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/YUeUKME.png", "flutterhide", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/z4PAdhi.png", "flutteroops", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/wwVpoHt.png", "flutterohmy", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/cSViT7t.png", "flutterterror", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/3UFhl3F.png", "fluttercute", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/968NYEH.png", "flutterjoy", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/HUbolAq.png", "flutterbride", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/Ade2YQ4.png", "flutterglee", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/nirPCDd.png", "fillyshy", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/MHYaQsA.png", "fluttermope", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/r4SxEH3.png", "flutterworry", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/xZjtFqi.png", "flutterunsure", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/5c1j3xv.png", "flutterhorrified", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/uSOX8aw.png", "fluttercontent", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/EcWBGKl.png", "flutteruhoh", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/hkeh1qO.png", "flutterdie", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/zFPxSbB.png", "flutterdisapprove", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/UgQIIgZ.png", "flutterannoyed", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/7LN4PGP.png", "fluttersheepish", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/Ar4a6oI.png", "fluttersing", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/Tsg6sSk.png", "flutterfret", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/3Bw1vJc.png", "flutterhelmet", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/09KvwZS.png", "fluttergrr", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/Pz8VqXm.png", "flutterhappy", "FS", "Fluttershy", 2);

	addEmote("http://i.imgur.com/N6frZ.png", "pinkiefear", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/EYLpq.png", "pinkieawe", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/ojb2X.png", "pinkiecute", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/30Blc.png", "pinkieboring", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/yGwJZ.png", "pinkieshrug", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/aMNtT.png", "pinkieseesyou", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/qO3Da.png", "pinkieohhi", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/UGWzB.png", "pinkieparty", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/477xD.png", "pinkielaugh", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/RXtaw.png", "pinkiejoy", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/uEidI.png", "pinkamina", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/xeWgy.png", "pinkiehuhhuh", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/zbei6cO.png", "pinkiestache", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/zplekGi.png", "pinkieunsure", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/jvzynek.png", "pinkiemute", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/LMtxcao.png", "pinkaboo", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/7ppPcYn.png", "partycannon", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/4doC5ED.png", "puddinghead", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/MQBZ41g.png", "pinkieglee", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/pdLkfXA.png", "pinkiewatchout", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/NwyjTTE.png", "pinkiecry", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/Q7KFdL7.png", "pinkieshock", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/q4uECGh.png", "pinkiesing", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/4M5fMay.png", "pinkiehither", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/8BDWuaI.png", "pinkiechew", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/sBq1PM1.png", "pinkiethrow", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/Ok4LXo8.png", "pinkiesatisfied", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/NH9sCfd.png", "pinkiecheck", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/4nGTfIp.png", "pinkiepieroll", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/ba6ZNCe.png", "pinkiesad", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/pfxW46W.png", "pinkiehurt", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/EOCIHpr.png", "pinkiesquee", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/guiiQT2.png", "pinkieglass", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/sBLaV.png", "pinkiewut", "PP", "Pinkie Pie", 2);

	addEmote("http://i.imgur.com/CGBhB.png", "raridaww", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/Ma3vZ.png", "rarireally", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/zbSFhpV.png", "raripaper", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/dObdk0h.png", "rarishock", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/i3eNB.png", "rariyell", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/TAnnF.png", "raridress", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/DHfUL.png", "rariwut", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/9YyaH.png", "rariwhy", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/DobP4.png", "rarityannoyed", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/DiqwR.png", "rariwhine", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/SUAwQ.png", "rarijudge", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/JT3f7.png", "rariprimp", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/u3SP8.png", "rarisad", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/ZkYG2.png", "rarifabulous", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/2tu9n.png", "rariwahaha", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/KluyWmn.png", "Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/cUszKbb.png", "Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/9yFw70j.png", "Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/hyH6usq.png", "Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/CpZgXTk.png", "Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/hT1CSak.png", "Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/HDAG3B9.png", "Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/tHHlMgs.png", "Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/GLRdqlz.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/dwryYQj.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/pqytDZN.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/JqAPTWq.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/mmVWxDL.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/YHqF6Oe.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/BTkTZtQ.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/ijHyYGN.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/H93RXx3.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/rqasPvb.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/qrNLnm7.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/gSUBQJo.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/L82FBf7.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/uUFRVSw.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/9cktQCa.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/FIMTF9F.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/6Xjr4qx.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/8FLpgzg.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/zDp89aN.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/E3hoUZ9.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/gB0LmNp.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/4rkfVbA.png", "Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/e3oGM6f.png", "Emote", "R", "Rarity", 2);

	addEmote("http://i.imgur.com/tCets.png", "rdcry", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/dB5nN.png", "rdsmile", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/Kv8nA.png", "rdwut", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/OzWNB.png", "rdawesome", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/jjgRs.png", "rdcool", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/oZUgV.png", "rdsitting", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/XtUF0.png", "rdhappy", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/o42xN.png", "rdannoyed", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/9HNfn.png", "rdgross", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/NRtTF.png", "rdlouder", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/CqXDDh6.png", "rdscared", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/QoZIz.png", "rdhuh", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/Y7iEz.png", "rdsalute", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/DN4kI.png", "rdawwyeah", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/fQFdk.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/5JXsL.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/drWSW.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/r1Eed.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/mI2kf.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/JJakx.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/2mIou.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/l49YA.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/Bo3i2.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/F4J97.png", "Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/99WZ6.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/KgKuu.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/ys5RX.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/m10uz.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/AJ9zx.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/81dJd.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/vc4Ok.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/e09RZ.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/Uvt7B.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/DupLe.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/Am3AY.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/7TZmw.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/72IFYgG.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/xq9lagn.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/Cqzgjte.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/fmPKYjE.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/ZaEN90U.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/1bcgbrm.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/aJbPeur.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/DuTtzKD.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/btqHYra.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/RpDP6ER.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/Giz33co.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/hn8oRP5.png", "Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/g63FgrH.png", "Emote", "RD", "Rainbow Dash", 2);

	addEmote("http://i.imgur.com/AhJQA.png", "twipride", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/teICa.png", "twicrazy", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/qDNQJ.png", "twibeam", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/ULdav.png", "twiright", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/NZ9LG.png", "twisquint", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/lyj7g.png", "twifacehoof", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/UQUPg.png", "twirage", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/uCBdE.png", "twismug", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/h6FPh.png", "twismile", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/Zvhzz.png", "twistare", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/5faXAtj.png", "twidaww", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/IbDeO.png", "twiponder", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/5OGeQ.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/hs7Hh.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/Srz3i.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/HlSYp.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/2652g.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/NmMWv.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/Ccokh.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/hgIE1.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/hRqZN.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/2hXpy.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/ZsI8b.png", "Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/fGB3u.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/1wjw2.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/wnSmS.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/r0Rhe.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/cCChp.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/UkpBz.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/MRdvo.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/OJHNg.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/IZJSZ.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/z2R9A.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/djjrzly.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/u91K3lE.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/6amBMsZ.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/8MaDTLV.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/SspLS12.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/SGKxDhn.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/OL1DowU.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/lSIizWD.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/JV1WARw.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/CV2Kxuv.png", "Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/OVnC2UC.png", "Emote", "TS", "Twilight Sparkle", 2);

	addEmote("http://i.imgur.com/DKLH4.png", "abmeh", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/6skeR.png", "abbored", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/yEdBp.png", "abwut", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/EKbat.png", "absmile", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/Ku52Y.png", "abhuh", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/JZ7Qjcd.png", "abuptosomething", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/8lobA8K.png", "abyay", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/CWD9YgU.png", "abdefeated", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/AHCUSzQ.png", "abmad", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/s9xv5RA.png", "abplead", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/K2NUEkN.png", "abpout", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/L3HMAWY.png", "abscared", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/oFJvsvt.png", "abmean", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/U60iZlB.png", "wackywavyinflatablearmflailingtubebloom", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/YeZuAdH.png", "abhuh", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/Sm8bW9r.png", "abinnocent", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/NZoImDq.png", "absurprised", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/oHyofJ3.png", "abcheerful", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/UjiYYXl.png", "cmcbiggrin", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/0V8u1Lz.png", "cmcbigsmile", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/uVj8R.png", "scootaderp", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/20x2X.png", "scootacheer", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/BxLgU.png", "scootaplease", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/gl6yp.png", "scootaloo", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/IMGC8.png", "cutealoo", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/fiITL.png", "scootapride", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/tDOuj3P.png", "scootarock", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/O7YJl8D.png", "scootabasket", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/5HOAGsD.png", "scootapost", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/kQc1R5l.png", "scootasurprised", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/sM1SH0r.png", "guiltyloo", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/rLhDpm3.png", "chicken", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/sYAzM.png", "ohcomeon", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/VViKq.png", "sbbook", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/DGsL3.png", "dumbfabric", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/dWaeV.png", "sbstare", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/inSsXQt.png", "sbscoot", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/Gh1mXeB.png", "sbrock", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/njZ7Ocd.png", "sbmischief", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/IfOQXKX.png", "sbscared", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/s461PaL.png", "sbsurprised", "CMC", "The Crusaders", 3);

	addEmote("http://i.imgur.com/TkVcM.png", "priceless", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/ZebG2.png", "celestiamad", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/Wtyb9.png", "celestiawut", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/j4frQ.png", "celestia", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/fIvet.png", "lunateehee", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/tkMRq.png", "lunawait", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/u9iJV.png", "lunasad", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/fH5FO.png", "lunagasp", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/0lMv9.png", "lunahappy", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/nh9dv.png", "nmm", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/Av7mi.png", "cadance", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/xJ9hG.png", "shiningarmor", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/TVh3T.png", "chrysalis", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/QwaS1.png", "spikemeh", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/YI5jr.png", "spikeletter", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/lebxZ.png", "spikenervous", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/QcNTf.png", "spikenoooo", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/qACFB.png", "spikepushy", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/BbPhC.png", "manspike", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/GmNPM.png", "allmybits", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/vBxYG.png", "spikewtf", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/pV4j88A.png", "changeling", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/VK1CV.png", "sotrue", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/Vhz4BpV.png", "ironwill", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/sHp29.png", "derpypaperbag", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/rv8JX.png", "derpyhappy", "MISC", "Other", 2);	
	addEmote("http://i.imgur.com/zI6pj.png", "derpyshock", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/BDNMW.png", "derp", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/ZQwXp.png", "grannysmith", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/cgoor.png", "swagintosh", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/wLZl0.png", "eeyup", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/P83z2.png", "macintears", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/4pRNpKu.png", "macwut", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/tF17M4z.png", "macready", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/REXzM.png", "trixiesmug", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/3Sr1ACU.png", "trixiesad", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/LbXFj.png", "trixiegap", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/6li8p6M.png", "trixiecreep", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/jorT3.png", "gilda", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/nXFjR.png", "spitfirecool", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/S46ae8h.png", "spitfire", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/GIV4g.png", "zecora", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/rTIx4.png", "photofinish", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/ZNGZn.png", "silverpout", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/UwaXc.png", "lyra", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/kXPdl.png", "bonbon", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/mmjN8.png", "octavia", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/BoPE4.png", "vinyl", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/W9ZCa.png", "punchdrunk", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/a9ddz.png", "colgate", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/xo9Mr.png", "whooves", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/MGw7s.png", "thehorror", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/lx5pI.png", "snails", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/eWyjh.png", "cockatrice", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/pjagI.png", "angelbunny", "MISC", "Other", 2);

}