// ==UserScript==
// @name Fimfiction Emote Extender
// @namespace ffemoteextender
// @description Adds additional emotes to fimfiction.net.
// @include http*://www.fimfiction.net/*
// @include http*://fimfiction.net/*
// @grant none
// @require https://raw.github.com/KrazyTheFox/Fimfiction-Emote-API/master/emoteAPI.js
// @version 2.0
// ==/UserScript==

$(document).ready(run());

function run() {
	
	addEmote("http://i.imgur.com/NBEDt.png", "ajemote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/5Tp73.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/oa0BJ.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/oaEI1BM.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/bEP8EQ2.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/mMp7L.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/HZlOi.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/7PYFy.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/DHDbq.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/8zRAx.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/aBIJ1.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/DmoWN.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/MdJgU.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/dVnqE.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/TAf9J.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/gNxjD.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/JmYib.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/aPZth.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/4sZY1.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/1NN8f.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/xmRQV.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/lGb8P.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/0zTKq.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/BeQHk.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/fl6ox.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/mbZjl.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/r19vB.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/hMgvT.png", "Test Emote", "AJ", "Applejack", 1);
	addEmote("http://i.imgur.com/ZCoEh.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/1ppRy.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/kjSfI.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/pwUmu.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/geqle.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/LOrxf.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/Evd0x.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/tjCXQ.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/NlvYtnA.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/Qe7TiLt.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/yAmRYea.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/pww1wjm.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/KZHFE8U.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/MZsrxQK.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/aHVIEJf.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/DPk2NZn.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/ogtnDnC.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/oBAx788.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/myOBKB4.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/LRD2W70.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/MIrVmT7.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/yyfj6BZ.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/6DvjrRv.png", "Test Emote", "AJ", "Applejack", 2);
	addEmote("http://i.imgur.com/0REqcvr.png", "Test Emote", "AJ", "Applejack", 2);

	addEmote("http://i.imgur.com/hCkff.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/FlxUX.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/Mpt2V.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/PKx4m.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/J1YdP.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/iX6uT.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/AUoqx.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/gphLa.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/eAjva.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/H718D.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/ahOjP.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/5wxoPUa.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/sb2Qbof.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/24nRCr5.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/AFuKMoD.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/mkCLMHb.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/IOcuWkK.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/YUeUKME.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/z4PAdhi.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/wwVpoHt.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/cSViT7t.png", "Test Emote", "FS", "Fluttershy", 1);
	addEmote("http://i.imgur.com/3UFhl3F.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/968NYEH.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/HUbolAq.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/Ade2YQ4.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/nirPCDd.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/MHYaQsA.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/r4SxEH3.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/xZjtFqi.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/5c1j3xv.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/uSOX8aw.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/EcWBGKl.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/hkeh1qO.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/zFPxSbB.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/UgQIIgZ.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/7LN4PGP.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/Ar4a6oI.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/Tsg6sSk.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/3Bw1vJc.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/09KvwZS.png", "Test Emote", "FS", "Fluttershy", 2);
	addEmote("http://i.imgur.com/Pz8VqXm.png", "Test Emote", "FS", "Fluttershy", 2);

	addEmote("http://i.imgur.com/N6frZ.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/EYLpq.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/ojb2X.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/30Blc.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/yGwJZ.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/aMNtT.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/qO3Da.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/UGWzB.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/477xD.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/RXtaw.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/uEidI.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/xeWgy.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/zbei6cO.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/zplekGi.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/jvzynek.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/LMtxcao.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/7ppPcYn.png", "Test Emote", "PP", "Pinkie Pie", 1);
	addEmote("http://i.imgur.com/4doC5ED.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/MQBZ41g.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/pdLkfXA.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/NwyjTTE.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/Q7KFdL7.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/q4uECGh.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/4M5fMay.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/8BDWuaI.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/sBq1PM1.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/Ok4LXo8.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/NH9sCfd.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/4nGTfIp.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/ba6ZNCe.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/pfxW46W.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/EOCIHpr.png", "Test Emote", "PP", "Pinkie Pie", 2);
	addEmote("http://i.imgur.com/guiiQT2.png", "Test Emote", "PP", "Pinkie Pie", 2);

	addEmote("http://i.imgur.com/CGBhB.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/Ma3vZ.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/zbSFhpV.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/dObdk0h.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/i3eNB.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/TAnnF.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/DHfUL.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/9YyaH.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/DobP4.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/DiqwR.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/SUAwQ.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/JT3f7.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/u3SP8.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/ZkYG2.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/2tu9n.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/KluyWmn.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/cUszKbb.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/9yFw70j.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/hyH6usq.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/CpZgXTk.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/hT1CSak.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/HDAG3B9.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/tHHlMgs.png", "Test Emote", "R", "Rarity", 1);
	addEmote("http://i.imgur.com/GLRdqlz.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/dwryYQj.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/pqytDZN.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/JqAPTWq.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/mmVWxDL.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/YHqF6Oe.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/BTkTZtQ.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/ijHyYGN.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/H93RXx3.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/rqasPvb.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/qrNLnm7.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/gSUBQJo.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/L82FBf7.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/uUFRVSw.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/9cktQCa.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/FIMTF9F.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/6Xjr4qx.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/8FLpgzg.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/zDp89aN.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/E3hoUZ9.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/gB0LmNp.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/4rkfVbA.png", "Test Emote", "R", "Rarity", 2);
	addEmote("http://i.imgur.com/e3oGM6f.png", "Test Emote", "R", "Rarity", 2);

	addEmote("http://i.imgur.com/tCets.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/dB5nN.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/Kv8nA.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/OzWNB.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/jjgRs.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/oZUgV.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/XtUF0.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/o42xN.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/9HNfn.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/NRtTF.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/CqXDDh6.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/QoZIz.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/Y7iEz.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/DN4kI.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/1mJFi.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/fQFdk.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/5JXsL.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/drWSW.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/r1Eed.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/mI2kf.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/JJakx.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/2mIou.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/l49YA.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/Bo3i2.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/F4J97.png", "Test Emote", "RD", "Rainbow Dash", 1);
	addEmote("http://i.imgur.com/99WZ6.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/KgKuu.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/ys5RX.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/m10uz.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/AJ9zx.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/81dJd.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/vc4Ok.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/e09RZ.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/Uvt7B.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/DupLe.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/Am3AY.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/7TZmw.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/72IFYgG.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/xq9lagn.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/Cqzgjte.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/fmPKYjE.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/ZaEN90U.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/1bcgbrm.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/aJbPeur.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/DuTtzKD.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/btqHYra.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/RpDP6ER.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/Giz33co.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/hn8oRP5.png", "Test Emote", "RD", "Rainbow Dash", 2);
	addEmote("http://i.imgur.com/g63FgrH.png", "Test Emote", "RD", "Rainbow Dash", 2);

	addEmote("http://i.imgur.com/AhJQA.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/teICa.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/qDNQJ.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/ULdav.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/NZ9LG.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/lyj7g.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/UQUPg.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/uCBdE.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/h6FPh.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/Zvhzz.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/5faXAtj.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/IbDeO.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/5OGeQ.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/hs7Hh.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/Srz3i.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/HlSYp.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/2652g.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/NmMWv.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/Ccokh.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/hgIE1.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/hRqZN.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/2hXpy.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/ZsI8b.png", "Test Emote", "TS", "Twilight Sparkle", 1);
	addEmote("http://i.imgur.com/fGB3u.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/1wjw2.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/wnSmS.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/r0Rhe.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/cCChp.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/UkpBz.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/MRdvo.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/OJHNg.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/IZJSZ.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/z2R9A.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/AKn7J.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/djjrzly.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/u91K3lE.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/6amBMsZ.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/8MaDTLV.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/SspLS12.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/SGKxDhn.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/OL1DowU.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/lSIizWD.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/JV1WARw.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/CV2Kxuv.png", "Test Emote", "TS", "Twilight Sparkle", 2);
	addEmote("http://i.imgur.com/OVnC2UC.png", "Test Emote", "TS", "Twilight Sparkle", 2);

	addEmote("http://i.imgur.com/DKLH4.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/6skeR.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/yEdBp.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/EKbat.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/Ku52Y.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/JZ7Qjcd.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/8lobA8K.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/CWD9YgU.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/AHCUSzQ.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/s9xv5RA.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/K2NUEkN.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/L3HMAWY.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/oFJvsvt.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/U60iZlB.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/YeZuAdH.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/Sm8bW9r.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/NZoImDq.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/oHyofJ3.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/UjiYYXl.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/0V8u1Lz.png", "Test Emote", "CMC", "The Crusaders", 1);
	addEmote("http://i.imgur.com/uVj8R.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/20x2X.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/BxLgU.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/gl6yp.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/IMGC8.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/fiITL.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/tDOuj3P.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/O7YJl8D.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/5HOAGsD.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/kQc1R5l.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/sM1SH0r.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/rLhDpm3.png", "Test Emote", "CMC", "The Crusaders", 2);
	addEmote("http://i.imgur.com/sYAzM.png", "Test Emote", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/VViKq.png", "Test Emote", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/DGsL3.png", "Test Emote", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/dWaeV.png", "Test Emote", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/inSsXQt.png", "Test Emote", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/Gh1mXeB.png", "Test Emote", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/njZ7Ocd.png", "Test Emote", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/IfOQXKX.png", "Test Emote", "CMC", "The Crusaders", 3);
	addEmote("http://i.imgur.com/s461PaL.png", "Test Emote", "CMC", "The Crusaders", 3);

	addEmote("http://i.imgur.com/TkVcM.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/ZebG2.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/Wtyb9.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/j4frQ.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/fIvet.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/tkMRq.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/u9iJV.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/fH5FO.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/0lMv9.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/nh9dv.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/Av7mi.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/xJ9hG.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/TVh3T.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/QwaS1.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/YI5jr.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/lebxZ.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/QcNTf.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/qACFB.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/BbPhC.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/GmNPM.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/vBxYG.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/pV4j88A.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/VK1CV.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/Vhz4BpV.png", "Test Emote", "MISC", "Other", 1);
	addEmote("http://i.imgur.com/sHp29.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/rv8JX.png", "Test Emote", "MISC", "Other", 2);	
	addEmote("http://i.imgur.com/zI6pj.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/BDNMW.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/ZQwXp.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/cgoor.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/wLZl0.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/P83z2.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/4pRNpKu.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/tF17M4z.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/REXzM.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/3Sr1ACU.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/LbXFj.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/jorT3.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/nXFjR.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/S46ae8h.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/GIV4g.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/rTIx4.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/ZNGZn.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/UwaXc.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/kXPdl.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/mmjN8.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/BoPE4.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/W9ZCa.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/a9ddz.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/xo9Mr.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/MGw7s.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/lx5pI.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/eWyjh.png", "Test Emote", "MISC", "Other", 2);
	addEmote("http://i.imgur.com/pjagI.png", "Test Emote", "MISC", "Other", 2);

}